oauth_login_oauth2.settings:
  type: mapping
  label: Settings
  mapping:
    miniorange_oauth_client_customer_admin_email:
      type: 'NULL'
    miniorange_oauth_client_customer_id:
      type: string
    miniorange_oauth_client_customer_admin_token:
      type: string
    miniorange_oauth_client_customer_api_key:
      type: string
    miniorange_oauth_client_name:
      type: string
    miniorange_oauth_client_status:
      type: string
    miniorange_oauth_client_customer_admin_phone:
      type: 'NULL'
    miniorange_oauth_client_tx_id:
      type: 'NULL'
    miniorange_oauth_client_customer_admin_password:
      type: string
    miniorange_oauth_client_base_url :
      type: string
    miniorange_oauth_enable_login_with_oauth:
      type: boolean
    miniorange_oauth_send_with_header_oauth:
      type: boolean
    miniorange_oauth_send_with_body_oauth:
      type: boolean